
-- Create Log Table
CREATE TABLE IF NOT EXISTS LOGS (LOG_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, DATED DATETIME NOT NULL, LOGGER VARCHAR(1000) NOT NULL, LEVEL VARCHAR(500) NOT NULL, MESSAGE VARCHAR(1000) NOT NULL);

-- Create Project Table
CREATE TABLE IF NOT EXISTS Personas (ID INT PRIMARY KEY AUTO_INCREMENT, Nombre VARCHAR(500), Apellido VARCHAR(500), Procesado VARCHAR(200));